---
- hosts: development
  vars:
    user:
      username: sam
      fullname: Sam Booth
      email: my@email.com
      home: /home/sam
  tasks:
    - name: variables
      debug:
        msg: "Username: {{ user['username'] }}, Home dir: {{ user['home'] }}"

    # This needs to happen first to enable the epel repo
    - name: epel install
      become: True
      ansible.builtin.package:
        name:
          oracle-epel-release-el{{ hostvars[inventory_hostname].ansible_distribution_major_version }}
        state: latest

    - name: Enable dev repos
      become: True
      command: "dnf config-manager --set-enabled ol{{ hostvars[inventory_hostname].ansible_distribution_major_version }}_developer ol{{ hostvars[inventory_hostname].ansible_distribution_major_version }}_codeready_builder"


     # It's really annoying I have to do this
    - name: Enable epel repos on 10
      command: "dnf config-manager --set-enabled ol10_u0_developer_EPEL"
      become: True
      when:
        - ansible_facts['distribution_major_version'] == "10"
    - name: Enable epel	repos on 9
      command: "dnf config-manager --set-enabled ol9_developer_EPEL"
      become: True
      when:
        - ansible_facts['distribution_major_version'] == "9"


    - name: User setup
      become: True
      user:
        name: "{{ user['username'] }}"
        groups:
         - wheel
        createhome: yes

    - name: Creates git folder
      become: True
      become_user: "{{ user['username'] }}"
      ansible.builtin.file:
        path: "/home/{{ user['username'] }}/git"
        state: directory
        mode: ug+rwx,o+rx

    - name: Dev install
      become: True
      ansible.builtin.package:
        name:
          - autoconf
          - autoconf-archive
          - rpmdevtools
          - rpmlint
          - mc
          - git
          - gcc
          - rpm-build
          - rpm-devel
          - make
          - python3
          - coreutils
          - diffutils
          - patch
          - vim
          - nano
        state: latest

    - name: Setup rpmtree
      become: True
      become_user: "{{ user['username'] }}"
      command: "chdir=/home/{{ user['username'] }}/ rpmdev-setuptree"

    - name: configure Git
      become: True
      become_user: "{{ user['username'] }}"
      command: "chdir=/home/{{ user['username'] }}/ git config --global user.name '{{ user['fullname'] }}'"

    - name: configure Git
      become: True
      become_user: "{{ user['username'] }}"
      command: "chdir=/home/{{ user['username'] }}/ git config --global user.email '{{ user['email'] }}'"

    - name: debug git
      debug:
        msg: "Name: {{ user['fullname'] }}, email: {{ user['email'] }}"

    - name: Dont overwrite your ssh key
      become: True
      become_user: "{{ user['username'] }}"
      stat:
        path: "/home/{{ user['username'] }}/.ssh/id_ecdsa"
      register: stat_result

    - name: ssh-key gen
      become: True
      become_user: "{{ user['username'] }}"
      command : "ssh-keygen -t ecdsa -N '' -C '{{ inventory_hostname }}' -f ~/.ssh/id_ecdsa "
      when: stat_result.stat.exists == False

    - name: Print message
      debug:
        msg: Ok you can ctrlc it now
